services:
  - type: web
    name: apnaadda
    runtime: node
    buildCommand: "echo Build complete"
    startCommand: node server.js
    envVars:
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
